# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FrmDataKen.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FrmDataKen(object):
    def setupUi(self, FrmDataKen):
        FrmDataKen.setObjectName("FrmDataKen")
        FrmDataKen.resize(379, 660)
        self.line_plat = QtWidgets.QLineEdit(FrmDataKen)
        self.line_plat.setGeometry(QtCore.QRect(40, 80, 171, 31))
        self.line_plat.setObjectName("line_plat")

        self.line_idparkir = QtWidgets.QLineEdit(FrmDataKen)
        self.line_idparkir.setGeometry(QtCore.QRect(40, 260, 171, 31))
        self.line_idparkir.setObjectName("line_idparkir")

        self.push_add = QtWidgets.QPushButton(FrmDataKen)
        self.push_add.setGeometry(QtCore.QRect(250, 80, 93, 28))
        self.push_add.setObjectName("push_add")
        self.push_delete = QtWidgets.QPushButton(FrmDataKen)
        self.push_delete.setGeometry(QtCore.QRect(250, 180, 93, 28))
        self.push_delete.setObjectName("push_delete")
        self.label = QtWidgets.QLabel(FrmDataKen)
        self.label.setGeometry(QtCore.QRect(40, 120, 101, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(FrmDataKen)
        self.label_2.setGeometry(QtCore.QRect(40, 60, 101, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(FrmDataKen)
        self.label_3.setGeometry(QtCore.QRect(40, 180, 121, 20))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(FrmDataKen)
        self.label_4.setGeometry(QtCore.QRect(40, 419, 121, 20))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(FrmDataKen)
        self.label_5.setGeometry(QtCore.QRect(40, 349, 101, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(FrmDataKen)
        self.label_6.setGeometry(QtCore.QRect(40, 490, 101, 16))
        self.label_6.setObjectName("label_6")
        self.temparkir = QtWidgets.QLabel(FrmDataKen)
        self.temparkir.setGeometry(QtCore.QRect(40, 310, 161, 31))
        self.temparkir.setObjectName("temparkir")
        self.temparkir_2 = QtWidgets.QLabel(FrmDataKen)
        self.temparkir_2.setGeometry(QtCore.QRect(40, 20, 191, 31))
        self.temparkir_2.setObjectName("temparkir_2")
        
        self.jeniskendaraan = QtWidgets.QLineEdit(FrmDataKen)
        self.jeniskendaraan.setGeometry(QtCore.QRect(40, 140, 171, 31))
        self.jeniskendaraan.setObjectName("jeniskendaraan")


        self.push_update = QtWidgets.QPushButton(FrmDataKen)
        self.push_update.setGeometry(QtCore.QRect(250, 130, 93, 28))
        self.push_update.setObjectName("push_update")
        self.noparkir = QtWidgets.QComboBox(FrmDataKen)
        self.noparkir.setGeometry(QtCore.QRect(40, 510, 171, 31))
        self.noparkir.setObjectName("noparkir")
        self.noparkir.addItem("")
        self.noparkir.addItem("")
        self.noparkir.addItem("")
        self.noparkir.addItem("")
        self.noparkir.addItem("")
        self.noparkir.addItem("")
        self.noparkir.addItem("")
        self.noparkir.addItem("")
        self.noparkir.addItem("")
        self.noparkir.addItem("")
        self.blokparkir = QtWidgets.QComboBox(FrmDataKen)
        self.blokparkir.setGeometry(QtCore.QRect(40, 370, 171, 31))
        self.blokparkir.setObjectName("blokparkir")
        self.blokparkir.addItem("")
        self.blokparkir.addItem("")
        self.blokparkir.addItem("")
        self.blokparkir.addItem("")
        self.blokparkir.addItem("")
        self.blokparkir.addItem("")
        self.lantai = QtWidgets.QComboBox(FrmDataKen)
        self.lantai.setGeometry(QtCore.QRect(40, 440, 171, 31))
        self.lantai.setObjectName("lantai")
        self.lantai.addItem("")
        self.lantai.addItem("")
        self.lantai.addItem("")
        self.label_7 = QtWidgets.QLabel(FrmDataKen)
        self.label_7.setGeometry(QtCore.QRect(40, 559, 101, 16))
        self.label_7.setObjectName("label_7")
        self.statusparkir = QtWidgets.QComboBox(FrmDataKen)
        self.statusparkir.setGeometry(QtCore.QRect(40, 580, 171, 31))
        self.statusparkir.setObjectName("statusparkir")
        self.statusparkir.addItem("")
        self.statusparkir.addItem("")
        self.label_8 = QtWidgets.QLabel(FrmDataKen)
        self.label_8.setGeometry(QtCore.QRect(40, 239, 121, 20))
        self.label_8.setObjectName("label_8")
        
        self.line_modelken_2 = QtWidgets.QLineEdit(FrmDataKen)
        self.line_modelken_2.setGeometry(QtCore.QRect(40, 201, 171, 31))
        self.line_modelken_2.setObjectName("line_modelken_2")

        #self.push_addp = QtWidgets.QPushButton(FrmDataKen)
        #elf.push_addp.setGeometry(QtCore.QRect(250, 370, 93, 28))
        #self.push_addp.setObjectName("push_addp")
        #self.push_updatep = QtWidgets.QPushButton(FrmDataKen)
        #self.push_updatep.setGeometry(QtCore.QRect(250, 420, 93, 28))
        #self.push_updatep.setObjectName("push_updatep")
        #self.push_deletep = QtWidgets.QPushButton(FrmDataKen)
        #self.push_deletep.setGeometry(QtCore.QRect(250, 470, 93, 28))
        #self.push_deletep.setObjectName("push_deletep")

        self.retranslateUi(FrmDataKen)
        QtCore.QMetaObject.connectSlotsByName(FrmDataKen)

    def retranslateUi(self, FrmDataKen):
        _translate = QtCore.QCoreApplication.translate
        FrmDataKen.setWindowTitle(_translate("FrmDataKen", "Form"))
        self.push_add.setText(_translate("FrmDataKen", "Add"))
        self.push_delete.setText(_translate("FrmDataKen", "Delete"))
        self.label.setText(_translate("FrmDataKen", "Jenis Kendaraan"))
        self.label_2.setText(_translate("FrmDataKen", "Plat Nomer"))
        self.label_3.setText(_translate("FrmDataKen", "Warna Kendaraan"))
        self.label_4.setText(_translate("FrmDataKen", "Lantai"))
        self.label_5.setText(_translate("FrmDataKen", "Blok"))
        self.label_6.setText(_translate("FrmDataKen", "Nomer Parkir"))
        self.temparkir.setText(_translate("FrmDataKen", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Tempat Parkir</span></p></body></html>"))
        self.temparkir_2.setText(_translate("FrmDataKen", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Identitas Kendaraan</span></p></body></html>"))

        self.push_update.setText(_translate("FrmDataKen", "Update"))

        self.noparkir.setItemText(0, _translate("FrmDataKen", "1"))
        self.noparkir.setItemText(1, _translate("FrmDataKen", "2"))
        self.noparkir.setItemText(2, _translate("FrmDataKen", "3"))
        self.noparkir.setItemText(3, _translate("FrmDataKen", "4"))
        self.noparkir.setItemText(4, _translate("FrmDataKen", "5"))
        self.noparkir.setItemText(5, _translate("FrmDataKen", "6"))
        self.noparkir.setItemText(6, _translate("FrmDataKen", "7"))
        self.noparkir.setItemText(7, _translate("FrmDataKen", "8"))
        self.noparkir.setItemText(8, _translate("FrmDataKen", "9"))
        self.noparkir.setItemText(9, _translate("FrmDataKen", "10"))

        self.blokparkir.setItemText(0, _translate("FrmDataKen", "A"))
        self.blokparkir.setItemText(1, _translate("FrmDataKen", "B"))
        self.blokparkir.setItemText(2, _translate("FrmDataKen", "C"))
        self.blokparkir.setItemText(3, _translate("FrmDataKen", "D"))
        self.blokparkir.setItemText(4, _translate("FrmDataKen", "E"))
        self.blokparkir.setItemText(5, _translate("FrmDataKen", "F"))

        self.lantai.setItemText(0, _translate("FrmDataKen", "G"))
        self.lantai.setItemText(1, _translate("FrmDataKen", "B1"))
        self.lantai.setItemText(2, _translate("FrmDataKen", "B2"))
        self.label_7.setText(_translate("FrmDataKen", "Status Parkir"))
        self.statusparkir.setItemText(0, _translate("FrmDataKen", "Terisi"))
        self.statusparkir.setItemText(1, _translate("FrmDataKen", "Kosong"))
        self.label_8.setText(_translate("FrmDataKen", "ID Parkir"))
        
        #self.push_addp.setText(_translate("FrmDataKen", "Add"))
        #self.push_updatep.setText(_translate("FrmDataKen", "Update"))
        #self.push_deletep.setText(_translate("FrmDataKen", "Delete"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FrmDataKen = QtWidgets.QMainWindow()
    ui = Ui_FrmDataKen()
    ui.setupUi(FrmDataKen)
    FrmDataKen.show()    
    sys.exit(app.exec_())
