from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import * 


class Ui_FrmLoginMainWindow(object):
    def setupUi(self, FrmLoginMainWindow):
        FrmLoginMainWindow.setObjectName("FrmLoginMainWindow")
        FrmLoginMainWindow.resize(334, 221)
        FrmLoginMainWindow.setMaximumSize(QtCore.QSize(334, 221))
        FrmLoginMainWindow.setGeometry(QtCore.QRect(100, 400, 334, 221))
        self.centralwidget = QtWidgets.QWidget(FrmLoginMainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(70, 80, 201, 81))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setHorizontalSpacing(23)
        self.formLayout.setObjectName("formLayout")
        self.userNameLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.userNameLabel.setObjectName("userNameLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.userNameLabel)
        self.Txt_username = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.Txt_username.setObjectName("Txt_username")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.Txt_username)
        self.passwordLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.passwordLabel.setObjectName("passwordLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.passwordLabel)
        self.Txt_password = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.Txt_password.setInputMask("")
        self.Txt_password.setObjectName("Txt_password")
        self.Txt_password.setEchoMode(QLineEdit.Password)
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.Txt_password)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 311, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 40, 311, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(70, 170, 201, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.PB_login = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.PB_login.setObjectName("PB_login")
        self.horizontalLayout.addWidget(self.PB_login)
        FrmLoginMainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(FrmLoginMainWindow)
        QtCore.QMetaObject.connectSlotsByName(FrmLoginMainWindow)

    def retranslateUi(self, FrmLoginMainWindow):
        _translate = QtCore.QCoreApplication.translate
        FrmLoginMainWindow.setWindowTitle(_translate("FrmLoginMainWindow", "Login"))
        self.userNameLabel.setText(_translate("FrmLoginMainWindow", "UserName"))
        self.passwordLabel.setText(_translate("FrmLoginMainWindow", "Password"))
        self.label.setText(_translate("FrmLoginMainWindow", "WELCOME TO F3 APARTMENT"))
        self.label_2.setText(_translate("FrmLoginMainWindow", "MANAGEMENT SYSTEM"))
        self.PB_login.setText(_translate("FrmLoginMainWindow", "Login"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FrmLoginMainWindow = QtWidgets.QMainWindow()
    ui = Ui_FrmLoginMainWindow()
    ui.setupUi(FrmLoginMainWindow)
    FrmLoginMainWindow.show()
    sys.exit(app.exec_())
