# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FrmOwner.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FrmOwner(object):
    def setupUi(self, FrmOwner):
        FrmOwner.setObjectName("FrmOwner")
        FrmOwner.resize(246, 314)
        self.centralwidget = QtWidgets.QWidget(FrmOwner)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 10, 241, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 40, 221, 266))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.idOwnerLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.idOwnerLabel.setObjectName("idOwnerLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.idOwnerLabel)
        self.Txt_id_owner = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.Txt_id_owner.setObjectName("Txt_id_owner")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.Txt_id_owner)
        self.Txt_tempatlahir = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.Txt_tempatlahir.setObjectName("Txt_tempatlahir")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.Txt_tempatlahir)
        self.passwordLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.passwordLabel.setObjectName("passwordLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.passwordLabel)
        self.labelkelamin = QtWidgets.QLabel(self.formLayoutWidget)
        self.labelkelamin.setObjectName("labelkelamin")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.labelkelamin)
        self.Cmb_kelamin = QtWidgets.QComboBox(self.formLayoutWidget)
        self.Cmb_kelamin.setEnabled(True)
        self.Cmb_kelamin.setEditable(True)
        self.Cmb_kelamin.setDuplicatesEnabled(False)
        self.Cmb_kelamin.setObjectName("Cmb_kelamin")
        self.Cmb_kelamin.addItem("")
        self.Cmb_kelamin.addItem("")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.Cmb_kelamin)
        self.PB_add = QtWidgets.QPushButton(self.formLayoutWidget)
        self.PB_add.setObjectName("PB_add")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.PB_add)
        self.PB_update = QtWidgets.QPushButton(self.formLayoutWidget)
        self.PB_update.setObjectName("PB_update")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.PB_update)
        self.PB_del = QtWidgets.QPushButton(self.formLayoutWidget)
        self.PB_del.setObjectName("PB_del")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.PB_del)
        self.PB_exit = QtWidgets.QPushButton(self.formLayoutWidget)
        self.PB_exit.setObjectName("PB_exit")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.PB_exit)
        self.tempatlahirLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.tempatlahirLabel.setObjectName("tempatlahirLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.tempatlahirLabel)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.Txt_nama = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.Txt_nama.setObjectName("Txt_nama")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.Txt_nama)
        self.Txt_telepon = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.Txt_telepon.setObjectName("Txt_telepon")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.Txt_telepon)
        self.labeltelepon = QtWidgets.QLabel(self.formLayoutWidget)
        self.labeltelepon.setObjectName("labeltelepon")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.labeltelepon)
        self.Txt_tanggallahir = QtWidgets.QDateEdit(self.formLayoutWidget)
        self.Txt_tanggallahir.setObjectName("Txt_tanggallahir")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.Txt_tanggallahir)
        FrmOwner.setCentralWidget(self.centralwidget)

        self.retranslateUi(FrmOwner)
        QtCore.QMetaObject.connectSlotsByName(FrmOwner)

    def retranslateUi(self, FrmOwner):
        _translate = QtCore.QCoreApplication.translate
        FrmOwner.setWindowTitle(_translate("FrmOwner", "Form Owner"))
        self.label.setText(_translate("FrmOwner", "OWNER"))
        self.idOwnerLabel.setText(_translate("FrmOwner", "Id Owner"))
        self.passwordLabel.setText(_translate("FrmOwner", "<html><head/><body><p>Tanggal lahir</p><p>(bln/tgl/thn)</p></body></html>"))
        self.labelkelamin.setText(_translate("FrmOwner", "Kelamin"))
        self.Cmb_kelamin.setItemText(0, _translate("FrmOwner", "pria"))
        self.Cmb_kelamin.setItemText(1, _translate("FrmOwner", "wanita"))
        self.PB_add.setText(_translate("FrmOwner", "Add"))
        self.PB_update.setText(_translate("FrmOwner", "Update"))
        self.PB_del.setText(_translate("FrmOwner", "Delete"))
        self.PB_exit.setText(_translate("FrmOwner", "Exit"))
        self.tempatlahirLabel.setText(_translate("FrmOwner", "Tempat lahir"))
        self.label_2.setText(_translate("FrmOwner", "Nama"))
        self.labeltelepon.setText(_translate("FrmOwner", "Telepon"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FrmOwner = QtWidgets.QMainWindow()
    ui = Ui_FrmOwner()
    ui.setupUi(FrmOwner)
    FrmOwner.show()
    sys.exit(app.exec_())
